### ISSUE TITLE
recurrence

### ISSUE THREAD

**Issue by sttzzz** [PRIS-CV/Bi-FRN#2]
Hello, you mentioned in your paper that CUB can use resnet12 as the backbone classification precision of 85.44±0.18 and 94.73±0.09, but I can only reach 82.85+-0.19 and 93.37+-0.1 by reproducing the precision. I have also studied the code and found that every module is used. Do you have any special Settings during the experiment?

**Comment by spraise** [comment]
> 

Thank you for your attention to our work. We clipped the boundaries of the CUB dataset and you needed to confirm that the split ratio in the split.txt was used.

**Comment by sttzzz** [comment]
> > 
> 
> Thank you for your attention to our work. We clipped the boundaries of the CUB dataset and you needed to confirm that the split ratio in the split.txt was used.

Yes, I used the cropped images and split them into train, validation and test sets according to split.txt

**Comment by spraise** [comment]
> > > 
> > 
> > 
> > Thank you for your attention to our work. We clipped the boundaries of the CUB dataset and you needed to confirm that the split ratio in the split.txt was used.
> 
> Yes, I used the cropped images and split them into train, validation and test sets according to split.txt

I re-ran the experiment, and the results were consistent with the paper. For the train, validation and test datasets, we all made cropped. I have uploaded the CUB dataset online.
